# ***Sistema de ecuaciones lineales***

***Definición***

Los sistemas de ecuaciones lineales (SEL) son conjuntos de ecuaciones lineales que se plantean simultáneamente y que involucran varias variables. Cada ecuación lineal en el sistema representa una relación lineal entre las variables desconocidas, y el objetivo es encontrar los valores de las variables que satisfacen todas las ecuaciones al mismo tiempo.

Para representar un sistema de ecuaciones lineales de forma matricial, se utilizan matrices y vectores. Las ecuaciones se agrupan en una matriz conocida como matriz de coeficientes, las incógnitas se agrupan en un vector y los términos constantes se agrupan en otro vector independiente. Resolver un sistema de ecuaciones lineales implica encontrar los valores del vector de incógnitas que hacen que todas las ecuaciones sean válidas.

Existen varios métodos para resolver sistemas de ecuaciones lineales, como el método de eliminación de Gauss-Jordan, el método de sustitución, el método de matriz inversa y el método de Cramer, entre otros. Estos métodos permiten encontrar las soluciones únicas del sistema en caso de que existan, o determinar si el sistema es inconsistente o tiene infinitas soluciones.

***Conceptos específicos:***

**Sistema de ecuaciones lineales:** es un conjunto de ecuaciones lineales que se resuelven al mismo tiempo para encontrar los valores de las variables que las satisfacen simultáneamente.

**Ecuación lineal:** es una expresión matemática en la que los términos consisten en constantes y variables multiplicadas por coeficientes.

**Solución de un sistema de ecuaciones:** es el conjunto de valores que hacen que todas las ecuaciones del sistema sean verdaderas. Dependiendo de la situación, el sistema puede tener una única solución, infinitas soluciones o ninguna solución.

In [1]:
import numpy as np

# Definir los coeficientes de las ecuaciones
A = np.array([[2, 3], [4, 1]])
B = np.array([8, 5])

# Resolver el sistema de ecuaciones
X = np.linalg.solve(A, B)

# Imprimir la solución
print("La solución del sistema es:")
print("x =", X[0])
print("y =", X[1])

La solución del sistema es:
x = 0.7
y = 2.2


In [2]:
import numpy as np

# Definir los coeficientes de las ecuaciones
A = np.array([[1, 2, -1], [3, 1, 4], [2, -3, 1]])
B = np.array([4, 9, 3])

# Resolver el sistema de ecuaciones
X = np.linalg.solve(A, B)

# Imprimir la solución
print("La solución del sistema es:")
print("x =", X[0])
print("y =", X[1])
print("z =", X[2])


La solución del sistema es:
x = 2.588235294117647
y = 0.7647058823529411
z = 0.11764705882352952


***Aplicación del teorema del Rouché Frobenius. Discusión de S.E.L.***

Es esencial para analizar sistemas de ecuaciones lineales (SEL) y proporciona información sobre sus soluciones. Se aplica al comparar los rangos de la matriz de coeficientes y la matriz ampliada del sistema. Si los rangos son iguales al número de incógnitas, el sistema tiene una solución única. Si el rango de la matriz de coeficientes es menor que el de la matriz ampliada, el sistema no tiene solución.

La discusión de un SEL implica determinar el número de incógnitas, escribir el sistema en forma matricial, calcular los rangos y compararlos. Si los rangos son consistentes con el número de incógnitas, hay una única solución. Si el rango de la matriz de coeficientes es menor, no hay solución. En otros casos, puede haber infinitas soluciones. Se pueden utilizar técnicas adicionales para expresar la solución del sistema, ya sea particular o paramétrica.

Es importante tener en cuenta que estos pasos son generales y pueden variar según la complejidad del sistema y sus características específicas. También existen otros métodos alternativos, como la matriz inversa y el determinante, que pueden aplicarse en situaciones particulares.

$$ \begin{equation}
\begin{pmatrix}
 1 & 1 & 2\\
 -4 & -1 & -5\\
 3 & 1 & 4
\end{pmatrix} 
\begin{pmatrix}
 x \\
 y \\
 z 
\end{pmatrix} =
\begin{pmatrix}
 b_{1} \\
 b_{2} \\
 b_{3}
\end{pmatrix}
\end{equation}$$

$$ \begin{equation}a) Si
\begin{pmatrix}
 b_{1} \\
 b_{2} \\
 b_{3}
\end{pmatrix} =
\begin{pmatrix}
 0 \\
 0 \\
 0
\end{pmatrix}, el \quad sistema \quad es \quad compatible \quad determinado. 
\end{equation}$$

$$ \begin{equation}b) Si
\begin{pmatrix}
 b_{1} \\
 b_{2} \\
 b_{3}
\end{pmatrix} =
\begin{pmatrix}
 1 \\
 1 \\
 1
\end{pmatrix}, el \quad sistema \quad es \quad compatible \quad indeterminado.
\end{equation}$$


Ejemplo: 

2x + 3y = 5
4x + 6y = 10

Podemos representar este sistema en forma matricial de la siguiente manera:

A * X = B

Donde:
A es la matriz de coeficientes: [[2, 3], [4, 6]]
X es el vector de incógnitas: [x, y]
B es el vector independiente: [5, 10]

A continuación, vamos a aplicar el teorema para determinar si el sistema tiene una solución única. 

In [3]:
import numpy as np

# Definir la matriz de coeficientes A
A = np.array([[2, 3], [4, 6]])

# Definir el vector independiente B
B = np.array([5, 10])

# Calcular el rango de la matriz de coeficientes
rango_coeficientes = np.linalg.matrix_rank(A)

# Combinar la matriz de coeficientes y el vector independiente en una matriz ampliada
matriz_ampliada = np.column_stack((A, B))

# Calcular el rango de la matriz ampliada
rango_ampliada = np.linalg.matrix_rank(matriz_ampliada)

# Comparar los rangos
if rango_coeficientes == rango_ampliada:
    if rango_coeficientes == len(A[0]):
        print("El sistema tiene una solución única.")
    else:
        print("El sistema tiene infinitas soluciones.")
else:
    print("El sistema no tiene solución.")


El sistema tiene infinitas soluciones.


Otro ejemplo:

3x - 2y = 4
6x - 4y = 8

Vamos a representar el sistema en forma matricial:

A * X = B

Donde:
A es la matriz de coeficientes: [[3, -2], [6, -4]]
X es el vector de incógnitas: [x, y]
B es el vector independiente: [4, 8]

A continuación, aplicaremos el teorema para determinar si el sistema tiene una solución única.

In [4]:
import numpy as np

# Definir la matriz de coeficientes A
A = np.array([[3, -2], [6, -4]])

# Definir el vector independiente B
B = np.array([4, 8])

# Calcular el rango de la matriz de coeficientes
rango_coeficientes = np.linalg.matrix_rank(A)

# Combinar la matriz de coeficientes y el vector independiente en una matriz ampliada
matriz_ampliada = np.column_stack((A, B))

# Calcular el rango de la matriz ampliada
rango_ampliada = np.linalg.matrix_rank(matriz_ampliada)

# Comparar los rangos
if rango_coeficientes == rango_ampliada:
    if rango_coeficientes == len(A[0]):
        print("El sistema tiene una solución única.")
    else:
        print("El sistema tiene infinitas soluciones.")
else:
    print("El sistema no tiene solución.")


El sistema tiene infinitas soluciones.


***Método de resolución: Matriz inversa; eliminación gaussiana***

El método de resolución mediante la matriz inversa es una técnica algebraica para resolver sistemas de ecuaciones lineales. Se puede resumir en los siguientes pasos:

1. Escribe el sistema de ecuaciones en forma matricial: AX = B, donde A es la matriz de coeficientes, X es el vector de variables y B es la matriz ampliada.

2. Calcula la matriz inversa de A: Si A es una matriz cuadrada y su determinante es diferente de cero, puedes calcular la matriz inversa utilizando métodos como la eliminación de Gauss-Jordan o la adjunta de la matriz.

3. Multiplica ambos lados de la ecuación por la matriz inversa de A: Obtendrás la ecuación X = A^(-1)B, donde X es el vector de variables.

4. Calcula el producto de la matriz inversa A^(-1) por la matriz ampliada B: Esto te dará el vector solución X, que representa los valores de las variables del sistema de ecuaciones.

Es importante tener en cuenta que calcular la matriz inversa puede ser computacionalmente costoso para matrices grandes, por lo que en la práctica se suelen utilizar métodos más eficientes, como la eliminación Gaussiana.

Matriz inicial:
$$
\begin{equation}
\begin{pmatrix}
 1 & 2 & 3 & | & 1 & 0 & 0 \\ 
 1 & 3 & 2 & | & 0 & 1 & 0 \\
 1 & 3 & 4 & | & 0 & 0 & 1 
\end{pmatrix} 
\end{equation}
$$

Paso 1: Restar la primera fila de las otras filas para hacer ceros en la columna 1 debajo del pivote.

$$
\begin{equation}
\begin{pmatrix}
 1 & 2 & 3 & | & 1 & 0 & 0 \\ 
 0 & 1 & -1 & | & -1 & 1 & 0 \\
 0 & 1 & 1 & | & -1 & 0 & 1 
\end{pmatrix} 
\end{equation}
$$

Paso 2: Restar la segunda fila de la tercera fila para hacer cero en la columna 2 debajo del pivote.

$$
\begin{equation}
\begin{pmatrix}
 1 & 2 & 3 & | & 1 & 0 & 0 \\ 
 0 & 1 & -1 & | & -1 & 1 & 0 \\
 0 & 0 & 2 & | & 0 & -1 & 1 
\end{pmatrix} 
\end{equation}
$$

Paso 3: Dividir la tercera fila por 2 para hacer el pivote de la columna 3 igual a 1.

$$
\begin{equation}
\begin{pmatrix}
 1 & 2 & 3 & | & 1 & 0 & 0 \\ 
 0 & 1 & -1 & | & -1 & 1 & 0 \\
 0 & 0 & 1 & | & 0 & -\frac{1}{2} & \frac{1}{2} 
\end{pmatrix} 
\end{equation}
$$

Paso 4: Restar la tercera fila multiplicada por 3 de la primera fila.

$$
\begin{equation}
\begin{pmatrix}
 1 & 2 & 0 & | & 1 & \frac{3}{2} & -\frac{3}{2} \\ 
 0 & 1 & -1 & | & -1 & 1 & 0 \\
 0 & 0 & 1 & | & 0 & -\frac{1}{2} & \frac{1}{2} 
\end{pmatrix} 
\end{equation}
$$

Paso 5: Restar la tercera fila de la segunda fila.

$$
\begin{equation}
\begin{pmatrix}
 1 & 2 & 0 & | & 1 & \frac{3}{2} & -\frac{3}{2} \\ 
 0 & 1 & 0 & | & -1 & \frac{3}{2} & -\frac{3}{2} \\
 0 & 0 & 1 & | & 0 & -\frac{1}{2} & \frac{1}{2} 
\end{pmatrix} 
\end{equation}
$$

Paso 6: Restar la segunda fila multiplicada por 2 de la primera fila.

$$
\begin{equation}
\begin{pmatrix}
 1 & 0 & 0 & | & 3 & -\frac{3}{2} & \frac{3}{2} \\ 
 0 & 1 & 0 & | & -1 & \frac{3}{2} & -\frac{3}{2} \\
 0 & 0 & 1 & | & 0 & -\frac{1}{2} & \frac{1}{2} 
\end{pmatrix} 
\end{equation}
$$

Por lo tanto, la solución del sistema de ecuaciones lineales es:

$$
\begin{align*}
x_1 &= 3 \\
x_2 &= -1 \\
x_3 &= 0
\end{align*}
$$

In [5]:
import numpy as np

# Definir la matriz de coeficientes
A = np.array([[2, 1, -1],
              [4, 1, 0],
              [-2, 2, 3]])

# Definir la matriz identidad del mismo tamaño que A
I = np.eye(3)

# Concatenar A e I para realizar la eliminación gaussiana simultáneamente
augmented_matrix = np.concatenate((A, I), axis=1)

# Aplicar eliminación gaussiana
n = augmented_matrix.shape[0]
for i in range(n):
    # Dividir la fila i por el pivote
    pivot = augmented_matrix[i, i]
    augmented_matrix[i] /= pivot
    
    # Eliminación hacia abajo
    for j in range(i + 1, n):
        factor = augmented_matrix[j, i]
        augmented_matrix[j] -= factor * augmented_matrix[i]
        
# Eliminación hacia arriba
for i in range(n - 1, 0, -1):
    for j in range(i - 1, -1, -1):
        factor = augmented_matrix[j, i]
        augmented_matrix[j] -= factor * augmented_matrix[i]
        
# Extraer la matriz inversa
inverse = augmented_matrix[:, n:]

print("Matriz inversa:")
print(inverse)


Matriz inversa:
[[-0.1875  0.3125 -0.0625]
 [ 0.75   -0.25    0.25  ]
 [-0.625   0.375   0.125 ]]


In [6]:
import numpy as np

# Definir la matriz de coeficientes
A = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])

# Definir la matriz identidad del mismo tamaño que A
I = np.eye(3)

# Concatenar A e I para realizar la eliminación gaussiana simultáneamente
augmented_matrix = np.concatenate((A, I), axis=1)

# Aplicar eliminación gaussiana
n = augmented_matrix.shape[0]
for i in range(n):
    # Dividir la fila i por el pivote
    pivot = augmented_matrix[i, i]
    augmented_matrix[i] /= pivot
    
    # Eliminación hacia abajo
    for j in range(i + 1, n):
        factor = augmented_matrix[j, i]
        augmented_matrix[j] -= factor * augmented_matrix[i]
        
# Eliminación hacia arriba
for i in range(n - 1, 0, -1):
    for j in range(i - 1, -1, -1):
        factor = augmented_matrix[j, i]
        augmented_matrix[j] -= factor * augmented_matrix[i]
        
# Extraer la matriz inversa
inverse = augmented_matrix[:, n:]

print("Matriz inversa:")
print(inverse)


Matriz inversa:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


***Eliminación de Gauss-Jordan***

Pasos clave para aplicar este método:

1. Escribe el sistema en forma matricial con la matriz de coeficientes y la matriz ampliada.

2. Utiliza operaciones elementales de fila para convertir la matriz de coeficientes en una matriz escalonada reducida por filas. Estas operaciones incluyen el intercambio de filas, la multiplicación de filas por un escalar y la suma/resta de filas multiplicadas por un escalar.

3. Después de la eliminación Gaussiana, la matriz escalonada resultante tendrá ceros debajo de la diagonal principal y puede estar en forma triangular superior.

4. Resuelve el sistema triangular superior mediante sustitución regresiva, comenzando desde la última ecuación y sustituyendo los valores conocidos en las ecuaciones anteriores para encontrar los valores de las variables desconocidas.

5. Reemplaza los valores de las variables encontrados en las ecuaciones originales para obtener la solución del sistema.

Es importante tener en cuenta que la eliminación Gaussiana puede revelar casos de ecuaciones contradictorias o redundantes, lo que indica que el sistema no tiene solución única o no tiene solución en absoluto.

In [8]:
import numpy as np

# Definir la matriz de coeficientes y el vector de constantes
A = np.array([[2, 1, -1],
              [3, 4, 2],
              [1, -1, 3]])

B = np.array([4, 5, 6])

# Combinar la matriz de coeficientes y el vector de constantes
AB = np.column_stack((A, B))

# Aplicar eliminación de Gauss-Jordan
rows, cols = AB.shape
for i in range(rows):
    # Pivote actual
    pivot = AB[i, i]
    
    # Dividir la fila actual por el pivote para obtener un coeficiente principal igual a 1
    AB[i, :] = pivot
    
    # Eliminar los coeficientes en las otras filas
    for j in range(rows):
        if j != i:
            factor = AB[j, i]
            AB[j, :] -= factor * AB[i, :]

# Extraer el vector solución
X = AB[:, -1]

print("La solución del sistema es:")
print(X)


La solución del sistema es:
[ 36 -12  -5]


In [10]:
import numpy as np

# Definir la matriz de coeficientes y el vector de constantes
A = np.array([[1, 2, -1],
              [2, 1, 3],
              [3, -1, 2]])

B = np.array([3, 4, 1])

# Combinar la matriz de coeficientes y el vector de constantes
AB = np.column_stack((A, B))

# Aplicar eliminación de Gauss-Jordan
rows, cols = AB.shape
for i in range(rows):
    # Pivote actual
    pivot = AB[i, i]
    
    # Dividir la fila actual por el pivote para obtener un coeficiente principal igual a 1
    AB[i, :] = pivot
    
    # Eliminar los coeficientes en las otras filas
    for j in range(rows):
        if j != i:
            factor = AB[j, i]
            AB[j, :] -= factor * AB[i, :]

# Extraer el vector solución
X = AB[:, -1]

print("La solución del sistema es:")
print(X)


La solución del sistema es:
[12 -6 -5]


***Regla de Cramer. Discusión de S.E.L.***

La regla de Cramer es un método utilizado para resolver sistemas de ecuaciones lineales (SEL) utilizando determinantes. Esta regla se basa en la propiedad de que si una matriz de coeficientes es no singular (su determinante es diferente de cero), entonces el sistema tiene una única solución.

La regla de Cramer establece que para resolver un SEL de n ecuaciones lineales con n incógnitas, debemos calcular el determinante de la matriz de coeficientes principal y los determinantes de las matrices obtenidas al reemplazar cada columna de coeficientes por el vector de términos constantes. La solución del sistema se obtiene dividiendo cada determinante parcial por el determinante principal.

Aquí están los pasos para aplicar la regla de Cramer:

1. Escribe el sistema de ecuaciones lineales en forma matricial: AX = B, donde A es la matriz de coeficientes, X es el vector de incógnitas y B es el vector de términos constantes.

2. Calcula el determinante del sistema principal: |A|.

3. Para cada incógnita Xi, reemplaza la columna i de A por el vector B y calcula el determinante: |Ai|. Este determinante representa el sistema con la columna i reemplazada.

4. La solución del sistema es Xi = |Ai| / |A| para cada incógnita.

La regla de Cramer proporciona una forma sistemática de encontrar la solución de un SEL, siempre y cuando la matriz de coeficientes sea no singular. Sin embargo, calcular los determinantes puede ser computacionalmente costoso para matrices grandes, por lo que este método es más eficiente en sistemas pequeños.

Es importante tener en cuenta que la regla de Cramer tiene sus limitaciones. No se puede aplicar cuando la matriz de coeficientes es singular (su determinante es cero) o cuando el sistema no tiene solución única. En esos casos, se requieren otros métodos de resolución, como la eliminación Gaussiana o la descomposición LU.

In [11]:
import numpy as np

def cramer_rule(coefficients, constants):
    n = len(coefficients)
    main_det = np.linalg.det(coefficients)  # Determinante de la matriz de coeficientes principal
    
    solutions = []
    
    for i in range(n):
        modified_coeffs = np.copy(coefficients)  # Copia de la matriz de coeficientes para cada incógnita
        modified_coeffs[:, i] = constants  # Reemplazo de la columna i por el vector de términos constantes
        det = np.linalg.det(modified_coeffs)  # Determinante con la columna i reemplazada
        solution = det / main_det  # Solución para la incógnita i
        solutions.append(solution)
    
    return solutions

# Ejemplo de sistema de ecuaciones lineales: 2x + y = 5, 3x - 4y = 2
coefficients = np.array([[2, 1], [3, -4]])
constants = np.array([5, 2])

solutions = cramer_rule(coefficients, constants)
print("Soluciones del sistema:")
print("x =", solutions[0])
print("y =", solutions[1])


Soluciones del sistema:
x = 2.0
y = 1.0


In [12]:
import numpy as np

def cramer_rule(coefficients, constants):
    n = len(coefficients)
    main_det = np.linalg.det(coefficients)  # Determinante de la matriz de coeficientes principal
    
    solutions = []
    
    for i in range(n):
        modified_coeffs = np.copy(coefficients)  # Copia de la matriz de coeficientes para cada incógnita
        modified_coeffs[:, i] = constants  # Reemplazo de la columna i por el vector de términos constantes
        det = np.linalg.det(modified_coeffs)  # Determinante con la columna i reemplazada
        solution = det / main_det  # Solución para la incógnita i
        solutions.append(solution)
    
    return solutions

# Ejemplo de sistema de ecuaciones lineales: 
# x + 2y - z = 3
# 2x - y + 3z = 7
# 4x + y + 2z = 1

coefficients = np.array([[1, 2, -1], [2, -1, 3], [4, 1, 2]])
constants = np.array([3, 7, 1])

solutions = cramer_rule(coefficients, constants)
print("Soluciones del sistema:")
print("x =", solutions[0])
print("y =", solutions[1])
print("z =", solutions[2])


Soluciones del sistema:
x = -8.999999999999996
y = 12.199999999999989
z = 12.399999999999999


***Descomposiciones
LU y su aplicación a los
sistemas de ecuaciones
lineales y a la inversión
de matrices.***

La descomposición LU es una técnica utilizada en álgebra lineal para factorizar una matriz en el producto de dos matrices, una matriz triangular inferior (L) y una matriz triangular superior (U). Esta descomposición se utiliza ampliamente en la resolución de sistemas de ecuaciones lineales y en la inversión de matrices.

La descomposición LU se define de la siguiente manera: dado una matriz cuadrada A, se busca descomponerla en el producto de dos matrices L y U tal que A = LU, donde L es una matriz triangular inferior con unos en la diagonal principal, y U es una matriz triangular superior. 

La descomposición LU se puede utilizar para resolver sistemas de ecuaciones lineales. Dado un sistema de ecuaciones lineales AX = B, donde A es la matriz de coeficientes, X es el vector de incógnitas y B es el vector de términos constantes, la descomposición LU se aplica de la siguiente manera:

1. Se descompone la matriz A en las matrices L y U utilizando el método de descomposición LU.

2. Se resuelven dos sistemas de ecuaciones lineales triangulares mediante sustitución hacia adelante y hacia atrás para encontrar los vectores Y y X, respectivamente. En el sistema triangular inferior LY = B, se resuelve para Y utilizando la sustitución hacia adelante. Luego, en el sistema triangular superior UX = Y, se resuelve para X utilizando la sustitución hacia atrás.

La descomposición LU también se utiliza en la inversión de matrices. Dada una matriz invertible A, se puede calcular su inversa utilizando la descomposición LU de la siguiente manera:

1. Se descompone la matriz A en las matrices L y U mediante el método de descomposición LU.

2. Se resuelven varios sistemas de ecuaciones lineales triangulares para encontrar las columnas de la matriz inversa. En cada sistema triangular inferior LY = I, donde I es la matriz identidad, se resuelve para las columnas de Y utilizando la sustitución hacia adelante. Luego, en el sistema triangular superior UX = Y, se resuelve para las columnas de X utilizando la sustitución hacia atrás.

La descomposición LU tiene varias ventajas, como la reutilización de la matriz triangular inferior y triangular superior para resolver múltiples sistemas de ecuaciones lineales con la misma matriz de coeficientes, lo que ahorra tiempo computacional. Sin embargo, la descomposición LU solo es posible si la matriz A es invertible y su descomposición existe.

En resumen, la descomposición LU es una herramienta útil en álgebra lineal que permite factorizar una matriz en el producto de dos matrices triangulares. Se utiliza para resolver sistemas de ecuaciones lineales y calcular la inversa de matrices de forma eficiente.

In [13]:
import numpy as np
from scipy.linalg import lu

# Definir la matriz de coeficientes A y el vector de términos constantes B
A = np.array([[2, -1, 3], [4, 1, -2], [1, 3, -1]])
B = np.array([7, 8, 3])

# Obtener la descomposición LU de la matriz A
P, L, U = lu(A)

# Resolver el sistema de ecuaciones lineales AX = B utilizando la descomposición LU
# Primero, resolver LY = B mediante sustitución hacia adelante
Y = np.linalg.solve(L, B)

# Luego, resolver UX = Y mediante sustitución hacia atrás
X = np.linalg.solve(U, Y)

# Imprimir la solución del sistema
print("La solución del sistema de ecuaciones es:")
print(X)


La solución del sistema de ecuaciones es:
[1.53658537 2.41463415 0.7804878 ]


In [14]:
import numpy as np
from scipy.linalg import lu, inv

# Definir la matriz A
A = np.array([[2, -1, 3], [4, 1, -2], [1, 3, -1]])

# Obtener la descomposición LU de la matriz A
P, L, U = lu(A)

# Obtener la matriz inversa utilizando la descomposición LU
A_inv = np.dot(np.linalg.inv(U), np.linalg.inv(L))

# Imprimir la matriz inversa
print("La matriz inversa de A es:")
print(A_inv)


La matriz inversa de A es:
[[ 0.19512195 -0.02439024  0.12195122]
 [-0.12195122  0.3902439   0.04878049]
 [-0.17073171  0.14634146  0.26829268]]
