# ***Transformaciones lineales.***

***Definición y ejemplos de transformaciones lineales. Representación matricial. Propiedades.***

Una transformación lineal es una función entre dos espacios vectoriales que preserva las operaciones de suma de vectores y multiplicación por un escalar. En otras palabras, si tenemos dos vectores u y v y un escalar c, la transformación lineal T debe cumplir las siguientes propiedades:

1. T(u + v) = T(u) + T(v): La transformación lineal T preserva la suma de vectores. Aplicar T a la suma de dos vectores es equivalente a la suma de las transformaciones de cada vector por separado.

2. T(cu) = cT(u): La transformación lineal T preserva la multiplicación por un escalar. Aplicar T al producto de un vector por un escalar es equivalente a multiplicar la transformación del vector por el mismo escalar.

La representación matricial de una transformación lineal se obtiene utilizando una matriz. Si T es una transformación lineal del espacio vectorial R^n al espacio vectorial R^m, entonces existe una matriz A de tamaño m x n tal que para cada vector columna u de tamaño n, el producto matricial A * u da como resultado la transformación T(u).

Las propiedades de las transformaciones lineales incluyen:

1. Preservación de la suma: T(u + v) = T(u) + T(v)
2. Preservación de la multiplicación escalar: T(cu) = cT(u)
3. Preservación del vector cero: T(0) = 0, donde 0 es el vector cero en el espacio vectorial de partida y llegada.
4. La imagen de una combinación lineal de vectores es igual a la combinación lineal de las imágenes de los vectores individuales.
5. La transformación lineal inversa existe si y solo si la matriz asociada a la transformación es invertible.

Un ejemplo de transformación lineal es la rotación en el plano. Si consideramos el espacio vectorial R^2, una transformación lineal de rotación de ángulo θ se puede representar mediante la matriz:

| cos(θ)  -sin(θ) |
| sin(θ)   cos(θ) |

Esta matriz toma un vector columna [x, y] y lo rota θ grados en sentido antihorario alrededor del origen.

In [1]:
import numpy as np

def linear_transformation(vector):
    # Definir la matriz de transformación lineal
    matrix = np.array([[3, 2], [1, -4]])
    
    # Aplicar la transformación lineal al vector de entrada
    result = np.dot(matrix, vector)
    
    return result

# Ejemplo de vector de entrada
input_vector = np.array([1, 2])

# Aplicar la transformación lineal al vector de entrada
output_vector = linear_transformation(input_vector)

print("Vector de entrada:", input_vector)
print("Vector de salida:", output_vector)

Vector de entrada: [1 2]
Vector de salida: [ 7 -7]


In [2]:
import numpy as np

def linear_transformation(vector):
    # Definir la matriz de transformación lineal
    matrix = np.array([[1, 2], [3, -2]])
    
    # Aplicar la transformación lineal al vector de entrada
    result = np.dot(matrix, vector)
    
    return result

# Ejemplo de vector de entrada
input_vector = np.array([1, 0])

# Aplicar la transformación lineal al vector de entrada
output_vector = linear_transformation(input_vector)

print("Vector de entrada:", input_vector)
print("Vector de salida:", output_vector)

Vector de entrada: [1 0]
Vector de salida: [1 3]


***Núcleo e imagen***

El núcleo y la imagen son conceptos importantes en el ámbito de los espacios vectoriales y las transformaciones lineales. Características principales:

1. Núcleo:
   El núcleo de una transformación lineal, también conocido como espacio nulo, es el conjunto de vectores de entrada que se mapean a cero en el espacio de salida. En otras palabras, es el conjunto de vectores de entrada que son transformados en el vector cero por la transformación lineal. El núcleo se denota como N(T) o Ker(T), donde T es la transformación lineal.
   
   Características:
   - El núcleo siempre contiene el vector cero.
   - Si el núcleo solo contiene el vector cero, se dice que la transformación lineal es inyectiva o un monomorfismo.
   - El núcleo puede ser un subespacio vectorial.
   - El rango del núcleo más el rango de la transformación lineal es igual a la dimensión del espacio de entrada.
   
2. Imagen (Rango):
   La imagen de una transformación lineal es el conjunto de todos los vectores de salida obtenidos al transformar todos los vectores de entrada. Es el subespacio generado por los vectores de salida. La imagen se denota como Im(T) o Range(T), donde T es la transformación lineal.
   
   Características:
   - La imagen siempre contiene al menos el vector cero.
   - Si la imagen abarca todo el espacio de salida, se dice que la transformación lineal es sobreyectiva o un epimorfismo.
   - La imagen puede ser un subespacio vectorial.
   - La dimensión de la imagen es igual al rango de la transformación lineal.
   
Es importante destacar que el núcleo y la imagen están estrechamente relacionados. En particular, si la transformación lineal es linealmente independiente, el núcleo y la imagen son complementos ortogonales en el espacio de entrada.


In [ ]:
import numpy as np

# Definición de la matriz de transformación lineal
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Cálculo del núcleo
null_space = np.linalg.null_space(A)
print("Núcleo (Kernel):")
print(null_space)

# Cálculo de la imagen
image = np.linalg.matrix_rank(A)
print("Imagen (Rango):")
print(image)


In [ ]:
import numpy as np

# Definición de la matriz de transformación lineal
A = np.array([[1, -2, 3], [-2, 4, -6], [1, -2, 3]])

# Cálculo del núcleo
null_space = np.linalg.null_space(A)
print("Núcleo (Kernel):")
print(null_space)

# Cálculo de la imagen
image = np.linalg.matrix_rank(A)
print("Imagen (Rango):")
print(image)


***Matrices de transformaciones lineales generales***

Las matrices de transformaciones lineales generales son matrices que representan transformaciones lineales en espacios vectoriales de dimensiones diferentes. A diferencia de las matrices de transformaciones lineales específicas, que están asociadas a una transformación particular, las matrices de transformaciones lineales generales son más flexibles y pueden representar una amplia gama de transformaciones.

Una matriz de transformación lineal general se define como una matriz de tamaño m x n, donde m es la dimensión del espacio vectorial de llegada y n es la dimensión del espacio vectorial de partida. Cada elemento de la matriz representa cómo la transformación lineal afecta a un vector específico.

Las matrices de transformaciones lineales generales tienen propiedades importantes:

1. Composición de transformaciones: Si tenemos dos matrices de transformaciones lineales generales A (de tamaño m x n) y B (de tamaño p x m), entonces la composición de las transformaciones representadas por A y B está dada por la multiplicación de matrices AB (de tamaño p x n).

2. Propiedades de linealidad: Las transformaciones lineales generales satisfacen las propiedades de linealidad, como la preservación de la suma de vectores y la multiplicación por un escalar.

3. Núcleo e imagen: Al igual que en las transformaciones lineales específicas, las matrices de transformaciones lineales generales también tienen un núcleo y una imagen asociados. El núcleo es el conjunto de vectores que se mapean a cero y la imagen es el conjunto de todos los vectores alcanzables por la transformación lineal.

4. Inversibilidad: Una matriz de transformación lineal general es invertible si y solo si su núcleo contiene solo el vector cero. En este caso, su inversa existe y representa la transformación inversa.

Las matrices de transformaciones lineales generales son una herramienta poderosa para representar y manipular transformaciones en espacios vectoriales de dimensiones diferentes.

In [9]:
import numpy as np

# Definición de la matriz de transformación lineal general
A = np.array([[1, 2, 3], [4, 5, 6]])

# Definición de un vector de entrada
x = np.array([1, 2, 3])

# Aplicar la transformación lineal a través de la multiplicación de matrices
y = np.dot(A, x)

print("Matriz de Transformación Lineal:")
print(A)

print("Vector de entrada:")
print(x)

print("Vector resultante después de la transformación:")
print(y)


Matriz de Transformación Lineal:
[[1 2 3]
 [4 5 6]]
Vector de entrada:
[1 2 3]
Vector resultante después de la transformación:
[14 32]


In [10]:
import numpy as np

# Definición de la matriz de transformación lineal general
A = np.array([[2, 1], [-1, 3]])

# Definición de un vector de entrada
x = np.array([4, 2])

# Aplicar la transformación lineal a través de la multiplicación de matrices
y = np.dot(A, x)

print("Matriz de Transformación Lineal:")
print(A)

print("Vector de entrada:")
print(x)

print("Vector resultante después de la transformación:")
print(y)


Matriz de Transformación Lineal:
[[ 2  1]
 [-1  3]]
Vector de entrada:
[4 2]
Vector resultante después de la transformación:
[10  2]


***Aplicaciones***

Algunas de las aplicaciones más comunes son:

1. Resolución de sistemas de ecuaciones lineales: Las matrices de transformaciones lineales permiten resolver sistemas de ecuaciones lineales utilizando métodos como la eliminación de Gauss, la factorización LU o la descomposición QR. Al representar las ecuaciones como una matriz de coeficientes, podemos aplicar transformaciones lineales para simplificar y resolver el sistema.

2. Análisis y transformaciones geométricas: las transformaciones lineales pueden representar rotaciones, traslaciones, escalados y proyecciones en el espacio. Mediante matrices de transformaciones lineales, podemos realizar estas operaciones de forma eficiente y precisa. 

3. Compresión y procesamiento de imágenes: Las imágenes digitales se pueden representar como matrices de píxeles. Mediante transformaciones lineales, como la transformada de Fourier, la transformada discreta del coseno (DCT) o la transformada wavelet, es posible comprimir y procesar imágenes de manera eficiente. Estas transformaciones permiten eliminar redundancias y representar la imagen de manera más compacta.

4. Codificación de información: Las matrices de transformaciones lineales se utilizan para codificar y decodificar información. 

5. Análisis de redes y sistemas: Las matrices de transformaciones lineales se utilizan para analizar redes complejas, como redes de comunicación, redes eléctricas o redes sociales. Por ejemplo, la matriz de incidencia se utiliza para representar las conexiones entre nodos en una red, y las transformaciones lineales se aplican para analizar propiedades estructurales y dinámicas de la red.



In [12]:
Resolución de sistemas de ecuaciones lineales
import numpy as np

# Matriz de coeficientes
A = np.array([[2, 3], [4, 5]])

# Vector de términos independientes
B = np.array([6, 7])

# Resolver el sistema de ecuaciones lineales Ax = B
x = np.linalg.solve(A, B)

print("Solución del sistema de ecuaciones lineales:")
print(x)


Solución del sistema de ecuaciones lineales:
[-4.5  5. ]


In [15]:
Transformaciones geométricas
import numpy as np

# Matriz de transformación lineal para una rotación de 90 grados en sentido antihorario
A = np.array([[0, -1], [1, 0]])

# Vector de entrada
x = np.array([2, 3])

# Aplicar la transformación lineal
y = np.dot(A, x)

print("Vector resultante después de la transformación:")
print(y)


Vector resultante después de la transformación:
[-3  2]
