# ***Valores y vectores propios***

***Matrices particionadas. Definición y propiedades***

Las matrices particionadas, también conocidas como matrices divididas o matrices bloque, son matrices que se dividen en bloques o submatrices más pequeñas. Estas submatrices pueden ser de diferentes dimensiones y se organizan en una estructura de bloques dentro de la matriz principal.

La notación general para una matriz particionada es la siguiente:

$$ \begin{equation}
\begin{pmatrix}
A_{11} & A_{12} & \cdots & A_{1n}\\
A_{21} & A_{22} &\cdots & A_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
A_{m1} & A_{m2} & \cdots & A_{mn}
\end{pmatrix}
\end{equation} $$

Donde cada bloque $A_{i\ j}$ es una submatriz de dimensiones ri x cj, y m y n son las dimensiones totales de la matriz particionada.

Algunas de las propiedades y características de las matrices particionadas son:

1. Operaciones: Las matrices particionadas permiten realizar operaciones matemáticas como suma, resta y multiplicación de matrices, teniendo en cuenta la estructura de bloques. Por ejemplo, la suma de dos matrices particionadas se realiza sumando los bloques correspondientes.

2. Inversa: Si una matriz particionada es invertible, su inversa también puede ser particionada en bloques correspondientes. Es decir, la inversa de una matriz particionada tiene una estructura similar a la matriz original.

3. Submatrices: Las matrices particionadas contienen submatrices más pequeñas como bloques. Estas submatrices pueden ser extraídas o manipuladas de manera individual para realizar cálculos específicos.

4. Resolución de sistemas de ecuaciones: Las matrices particionadas se utilizan en la resolución de sistemas de ecuaciones lineales. Al particionar una matriz de coeficientes, es posible realizar operaciones específicas en cada bloque para simplificar el sistema y encontrar soluciones.

5. Representación de estructuras de datos: En ciencias de la computación, las matrices particionadas se utilizan para representar estructuras de datos complejas. Por ejemplo, una matriz particionada puede representar una matriz dispersa donde los bloques no nulos contienen información relevante.

Las matrices particionadas ofrecen una forma conveniente de organizar y manipular datos en bloques más pequeños, lo que puede facilitar el análisis y el cálculo en diversos contextos.

In [1]:
import numpy as np

# Matriz original
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# Particionar la matriz en bloques
A11 = A[:2, :2]  # Submatriz 2x2 en la esquina superior izquierda
A12 = A[:2, 2:]  # Submatriz 2x2 en la esquina superior derecha
A21 = A[2:, :2]  # Submatriz 1x2 en la esquina inferior izquierda
A22 = A[2:, 2:]  # Submatriz 1x2 en la esquina inferior derecha

# Imprimir las submatrices
print("Submatriz A11:")
print(A11)
print("Submatriz A12:")
print(A12)
print("Submatriz A21:")
print(A21)
print("Submatriz A22:")
print(A22)


Submatriz A11:
[[1 2]
 [5 6]]
Submatriz A12:
[[3 4]
 [7 8]]
Submatriz A21:
[[ 9 10]]
Submatriz A22:
[[11 12]]


In [2]:
import numpy as np

# Matriz original
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])

# Particionar la matriz en bloques
A1 = A[:2, :]    # Submatriz 2x3 en la parte superior
A2 = A[2:, :]    # Submatriz 2x3 en la parte inferior

# Imprimir las submatrices
print("Submatriz A1:")
print(A1)
print("Submatriz A2:")
print(A2)


Submatriz A1:
[[1 2 3]
 [4 5 6]]
Submatriz A2:
[[ 7  8  9]
 [10 11 12]]


In [3]:
import numpy as np

# Matriz original
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# Particionar la matriz en bloques
A1 = A[:, :2]    # Submatriz 3x2 en la parte izquierda
A2 = A[:, 2:]    # Submatriz 3x2 en la parte derecha

# Imprimir las submatrices
print("Submatriz A1:")
print(A1)
print("Submatriz A2:")
print(A2)


Submatriz A1:
[[ 1  2]
 [ 5  6]
 [ 9 10]]
Submatriz A2:
[[ 3  4]
 [ 7  8]
 [11 12]]


***Vectores y valores
propios. Ecuación y
Polinomio característico***

Los vectores y valores propios son conceptos importantes en la teoría de matrices y transformaciones lineales. Están relacionados con las características fundamentales de una matriz y proporcionan información valiosa sobre su comportamiento. Definición y propiedades de los vectores y valores propios, así como la ecuación y polinomio característico asociados. 

- Valor propio: Un valor propio (también llamado autovalor) de una matriz cuadrada A es un escalar λ tal que cuando se le aplica A a un vector no nulo x, el resultado es un múltiplo escalar de x, es decir, Ax = λx. En otras palabras, el vector x no cambia de dirección, solo se escala por un factor λ. El valor propio λ puede ser real o complejo.

- Vector propio: Un vector propio (también llamado autovector) corresponde a un valor propio y es un vector no nulo x que satisface la ecuación Ax = λx. El vector propio es importante porque representa la dirección en la cual ocurre el estiramiento o contracción característico de la matriz A.

- Ecuación característica: La ecuación característica es una ecuación matemática que se utiliza para encontrar los valores propios de una matriz. Para una matriz cuadrada A de tamaño n, la ecuación característica se define como det(A - λI) = 0, donde det() es el determinante, λ es el valor propio desconocido y I es la matriz identidad de tamaño n. Resolver esta ecuación proporciona los valores propios λ de la matriz A.

- Polinomio característico: El polinomio característico es una expresión algebraica obtenida a partir de la ecuación característica al expandir el determinante. El polinomio característico se representa como P(λ) = det(A - λI) y es una función polinómica en λ. Las raíces de este polinomio son los valores propios de la matriz A.

En resumen, los valores propios y vectores propios son elementos clave para comprender el comportamiento de una matriz. A través de la ecuación y polinomio característico, podemos determinar los valores propios y utilizarlos para analizar las propiedades y transformaciones asociadas con la matriz.

In [4]:
import numpy as np

# Definición de la matriz
A = np.array([[3, 1], [2, 2]])

# Cálculo de los valores y vectores propios
eigenvalues, eigenvectors = np.linalg.eig(A)

# Imprimir los valores propios
print("Valores propios:")
for eigenvalue in eigenvalues:
    print(eigenvalue)

# Imprimir los vectores propios
print("Vectores propios:")
for eigenvector in eigenvectors.T:
    print(eigenvector)

# Cálculo de la ecuación característica
characteristic_eq = np.poly(A)
print("Ecuación característica:")
print(characteristic_eq)

# Cálculo del polinomio característico
polynomial = np.poly1d(characteristic_eq)
print("Polinomio característico:")
print(polynomial)


Valores propios:
4.0
1.0
Vectores propios:
[0.70710678 0.70710678]
[-0.4472136   0.89442719]
Ecuación característica:
[ 1. -5.  4.]
Polinomio característico:
   2
1 x - 5 x + 4


In [6]:
import numpy as np

# Definición de la matriz
A = np.array([[4, 2, 1], [2, 3, 1], [1, 1, 2]])

# Cálculo de los valores y vectores propios
eigenvalues, eigenvectors = np.linalg.eig(A)

# Imprimir los valores propios
print("Valores propios:")
for eigenvalue in eigenvalues:
    print(eigenvalue)

# Imprimir los vectores propios
print("Vectores propios:")
for eigenvector in eigenvectors.T:
    print(eigenvector)

# Cálculo de la ecuación característica
characteristic_eq = np.poly(A)
print("Ecuación característica:")
print(characteristic_eq)

# Cálculo del polinomio característico
polynomial = np.poly1d(characteristic_eq)
print("Polinomio característico:")
print(polynomial)


Valores propios:
6.0489173395223075
1.6431041321077906
1.3079785283699041
Vectores propios:
[0.73697623 0.59100905 0.32798528]
[ 0.59100905 -0.32798528 -0.73697623]
[ 0.32798528 -0.73697623  0.59100905]
Ecuación característica:
[  1.  -9.  20. -13.]
Polinomio característico:
   3     2
1 x - 9 x + 20 x - 13


***Teorema de Cayley -
Hamilton.***

El teorema de Cayley-Hamilton establece que toda matriz cuadrada satisface su propia ecuación característica. Es decir, si A es una matriz cuadrada de tamaño nxn y p(x) es el polinomio característico de A, entonces al evaluar p(A) se obtiene la matriz cero.

En otras palabras, si p(x) = det(A - xI) es el polinomio característico de A, donde I es la matriz identidad, entonces al sustituir A en lugar de x en p(x), se obtiene la matriz cero:

p(A) = det(A - AI) = det(A - A) = det(O) = O

donde O es la matriz cero de tamaño nxn.

Permite calcular potencias de matrices de forma más eficiente, ya que cualquier potencia de la matriz puede expresarse en términos de las potencias de sus valores propios.

Además, el teorema de Cayley-Hamilton es utilizado en el cálculo de la inversa de una matriz, ya que permite expresar la matriz inversa en términos de la matriz misma y sus potencias.


In [8]:
import numpy as np

# Definición de la matriz A
A = np.array([[1, 2], [3, 4]])

# Cálculo del polinomio característico de A
p = np.poly(A)
print("Polinomio característico de A:", p)

# Evaluación de p(A)
p_A = np.polyval(p, A)
print("p(A):", p_A)

# Verificación de p(A) = 0
print("¿p(A) = 0?:", np.allclose(p_A, np.zeros_like(A)))


Polinomio característico de A: [ 1. -5. -2.]
p(A): [[-6. -8.]
 [-8. -6.]]
¿p(A) = 0?: False


In [9]:
import numpy as np

# Definición de la matriz A
A = np.array([[2, -1, 3], [0, 1, 2], [-1, 2, 0]])

# Cálculo del polinomio característico de A
p = np.poly(A)
print("Polinomio característico de A:", p)

# Evaluación de p(A)
p_A = np.polyval(p, A)
print("p(A):", p_A)

# Verificación de p(A) = 0
print("¿p(A) = 0?:", np.allclose(p_A, np.zeros_like(A)))


Polinomio característico de A: [ 1. -3.  1.  3.]
p(A): [[ 1. -2.  6.]
 [ 3.  2.  1.]
 [-2.  1.  3.]]
¿p(A) = 0?: False


***Diagonalización de
matrices***

La diagonalización de matrices es un proceso importante en el álgebra lineal que consiste en descomponer una matriz en una forma especial, donde la matriz resultante es diagonal y los vectores propios juegan un papel fundamental.

En general, una matriz cuadrada A se puede diagonalizar si cumple con las siguientes condiciones:

1. La matriz debe ser diagonalizable, lo cual implica que debe tener un conjunto completo de vectores propios linealmente independientes.

2. Los vectores propios asociados a cada valor propio deben formar una base del espacio vectorial correspondiente.

El proceso de diagonalización implica los siguientes pasos:

1. Calcular los valores propios de la matriz A resolviendo la ecuación característica: det(A - λI) = 0, donde λ representa el valor propio y I es la matriz identidad.

2. Para cada valor propio, encontrar el vector propio correspondiente resolviendo la ecuación (A - λI)v = 0, donde v es el vector propio.

3. Construir la matriz P utilizando los vectores propios encontrados. Los vectores propios deben ser colocados como columnas de la matriz P.

4. Calcular la matriz diagonal D, donde los valores propios se colocan en la diagonal principal.

5. Obtener la matriz A diagonalizada mediante la fórmula: A = PDP^(-1).

La diagonalización de una matriz es útil en varios aspectos, ya que permite simplificar los cálculos y el análisis de las propiedades de la matriz. Por ejemplo, las potencias sucesivas de una matriz diagonalizada son fáciles de calcular, y ciertas operaciones como la exponenciación y la inversión de matrices se vuelven más sencillas.

Es importante destacar que no todas las matrices son diagonalizables. Algunas matrices no tienen suficientes vectores propios linealmente independientes o no cumplen con los requisitos necesarios para la diagonalización. En esos casos, se pueden utilizar técnicas alternativas, como la descomposición en valores singulares (SVD) o la forma canónica de Jordan, para analizar y descomponer la matriz.

In [12]:
import numpy as np

# Definición de la matriz
A = np.array([[2, 1], [4, 3]])

# Obtener los valores y vectores propios
eigenvalues, eigenvectors = np.linalg.eig(A)

# Crear la matriz diagonal de valores propios
D = np.diag(eigenvalues)

# Crear la matriz de vectores propios invertida
P = np.linalg.inv(eigenvectors)

# Obtener la matriz diagonalizada
diagonalized = np.dot(np.dot(P, D), eigenvectors)

# Imprimir la matriz diagonalizada
print("Matriz diagonalizada:")
print(diagonalized)


Matriz diagonalizada:
[[ 2.         -1.72734465]
 [-2.31569305  3.        ]]


In [13]:
import numpy as np

# Definición de la matriz
A = np.array([[5, 2], [2, 3]])

# Obtener los valores y vectores propios
eigenvalues, eigenvectors = np.linalg.eig(A)

# Crear la matriz diagonal de valores propios
D = np.diag(eigenvalues)

# Crear la matriz de vectores propios invertida
P = np.linalg.inv(eigenvectors)

# Obtener la matriz diagonalizada
diagonalized = np.dot(np.dot(P, D), eigenvectors)

# Imprimir la matriz diagonalizada
print("Matriz diagonalizada:")
print(diagonalized)


Matriz diagonalizada:
[[ 5. -2.]
 [-2.  3.]]
